name: BPenv
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.8
    - astroid==2.4.2
    - cdtw==0.0.1
    - certifi==2020.12.5
    - colorama==0.4.4
    - cycler==0.10.0
    - Cython==0.29.21
    - dcor==0.5.3
    - dtaidistance==2.2.4
    - dtw-python==1.1.6
    - fastdtw==0.3.4
    - isort==5.6.4
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.4.3
    - llvmlite==0.36.0
    - matplotlib==3.3.3
    - mccabe==0.6.1
    - nose==1.3.7
    - numba==0.53.1
    - numpy==1.20.1
    - pandas==1.1.5
    - Pillow==8.0.1
    - pycodestyle==2.6.0
    - pylint==2.6.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - similaritymeasures==0.4.4
    - six==1.15.0
    - soft-dtw==0.1.dev0
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - wincertstore==0.2
    - wrapt==1.12.1